language: cpp
sudo: required
dist: focal

addons:
  apt:
    packages:
      - rpm
      - cmake
      - build-essential

before_script:
  - sudo apt-get update
  - sudo apt-get install -y cmake

script:
  - cmake -H. -B_build
  - cmake --build _build
  - cd _build
  - cpack -G DEB
  - cpack -G RPM

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: _build/*.deb
  skip_cleanup: true
  on:
    tags: true
    branch: main
